//HintName: Test.CafUsage.WriteAsync.g.cs
// <auto-generated/>
#nullable enable
namespace Test;
static partial class CafUsage
{
    static void Write(global::System.ReadOnlySpan<byte> buffer, global::System.IO.Stream stream)
        => stream.Write(buffer);
}
